version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    environment:
      - RAILS_ENV=production
    stdin_open: true
    tty: true

volumes:
  public-data:
  log-data:
  tmp-data:
