development:
  clients:
    default:
      database: mongodb

      hosts:
        - mongodb:27017
      options:
        user: "root"
        password: "root"
        server_selection_timeout: 1
        auth_source: admin
        auth_mech: :scram
  options:

test:
  clients:
    default:
      database: app_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: <%= Rails.application.credentials.mongoid[:uri] %>
      options:
        server_selection_timeout: 5
